Contact Form
mohamedSabry0/cr_contact_form pull request #1
Opened 2021-07-01 15:39 UTC by mohamedSabry0

Features implemented in this PR:
- Added form HTML skeleton.
- Implemented styling following the design pointed in the readme.
- Added form action.

2021-07-01 18:25 UTC, tahiry-dev requested changes
Hello mohamedSabry0 👋
You did a great job creating this contact form 💪 💪  ,
 but we need to implement more control to our form before moving to the next step 🤞🤞

## Required Changes ♻️
_Kindly limit the number of characters your name field could accept._
_And add validation to your form._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-01 18:25 UTC, tahiry-dev commented on index.html
> +          <input type="text" name="full-name" placeholder="Name">
Please limit the number of characters name field could accept

2021-07-01 18:25 UTC, tahiry-dev commented on index.html
> +          <button type="submit" class="form-submit">Get in touch</button>
Please prevent your user to send the form if one or more fields are empty.
As a quick reminder, here is the screenshot of the requirements:
![requirements](https://user-images.githubusercontent.com/47100064/124171211-ed950e00-dab0-11eb-9070-90247870db3b.png)

2021-07-01 20:40 UTC, umairarshadbutt approved these changes
Hi @mohamedSabry0 , 

Your project is complete!  You have implemented the suggested changes... I suggest you some optional change before merge :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Please remove `!important` from CSS file.
- Please update your live link.
- Please improve the contact form design.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-07-02 15:40 UTC, ahcodes approved these changes

2022-07-13 16:04 UTC, merged